import express from "express";
import { publicRouter } from "../routes/public-api.js";
import { errorMiddleware } from "../middleware/errorMiddleware.js";
import { userRouter } from "../routes/api.js";
import cors from "cors";
export const web = express();
web.use(cors());
web.use(express.json());
web.use(publicRouter);
web.use(userRouter);
web.use(errorMiddleware);
